name: Accessibility Testing

on:
  workflow_run:
    workflows: ['pages-build-deployment']
    types:
      - completed

jobs:
  run-accessibility-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Set up Node environment
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b
        with:
          node-version: 18.x

      - name: Install project dependencies
        run: yarn ci

      - name: Install global dependencies
        run: yarn install -g @unlighthouse/cli puppeteer

      - name: Run Tests
        run: unlighthouse-ci --config-file unlighthouse.config.ts --build-static --reporter jsonExpanded --debug
