name: Code Quality Checks

on:
  pull_request:
    branches: [main]

jobs:
  run-test-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Set up Node environment
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn ci

      - name: Run Vitest tests with coverage
        run: yarn run test:coverage

  run-lint-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Set up Node environment
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn ci

      - name: Lint code
        run: yarn run lint

  run-formatting-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Set up Node environment
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b
        with:
          node-version: 18.x

      - name: Install dependencies
        run: yarn ci

      - name: Format code
        run: yarn run format
