name: End-to-end Testing
on:
  workflow_run:
    workflows: ['pages-build-deployment']
    types:
      - completed
permissions:
  contents: write
jobs:
  run-e2e-testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Set up Node environment
        uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install -g yarn && yarn

      - name: Install Playwright Browsers
        run: yarn playwright install --with-deps

      - name: Run Tests
        run: yarn run e2e:ci
        env:
          APP_BASE_URL: /comet-starter/

      - uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b
        if: always()
        with:
          name: playwright-output
          path: playwright/output
          retention-days: 30
